"""empty message

Revision ID: 28af7e2a1d5e
Revises: 7ef7e63ba3c1
Create Date: 2023-10-31 00:18:56.481929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28af7e2a1d5e'
down_revision = '7ef7e63ba3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_email')
        batch_op.create_index(batch_op.f('ix_posts_email'), ['email'], unique=False)
        batch_op.drop_index('ix_posts_phone')
        batch_op.create_index(batch_op.f('ix_posts_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_phone'))
        batch_op.create_index('ix_posts_phone', ['phone'], unique=False)
        batch_op.drop_index(batch_op.f('ix_posts_email'))
        batch_op.create_index('ix_posts_email', ['email'], unique=False)

    # ### end Alembic commands ###
