"""posts

Revision ID: 449820bfd07e
Revises: 517483278e73
Create Date: 2023-10-29 00:44:42.054447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449820bfd07e'
down_revision = '517483278e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_description')
        batch_op.create_index(batch_op.f('ix_posts_description'), ['description'], unique=False)
        batch_op.drop_index('ix_posts_title')
        batch_op.create_index(batch_op.f('ix_posts_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_title'))
        batch_op.create_index('ix_posts_title', ['title'], unique=False)
        batch_op.drop_index(batch_op.f('ix_posts_description'))
        batch_op.create_index('ix_posts_description', ['description'], unique=False)

    # ### end Alembic commands ###
