"""posts

Revision ID: 517483278e73
Revises: 71839e118f0c
Create Date: 2023-10-29 00:16:00.227095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517483278e73'
down_revision = '71839e118f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_phone'))
        batch_op.drop_index(batch_op.f('ix_posts_email'))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
