"""Create Posts Table

Revision ID: 71839e118f0c
Revises: c71c84ebf6bc
Create Date: 2023-10-22 11:31:04.232670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71839e118f0c'
down_revision = 'c71c84ebf6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('ImageA', sa.LargeBinary(), nullable=True),
    sa.Column('ImageB', sa.LargeBinary(), nullable=True),
    sa.Column('ImageC', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_title'))
        batch_op.drop_index(batch_op.f('ix_posts_description'))
        batch_op.drop_index(batch_op.f('ix_posts_city'))

    op.drop_table('posts')
    op.drop_table('request')
    # ### end Alembic commands ###
