"""posts table

Revision ID: 7ef7e63ba3c1
Revises: 449820bfd07e
Create Date: 2023-10-30 21:32:38.285756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef7e63ba3c1'
down_revision = '449820bfd07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('ImageA',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('ImageB',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('ImageC',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('ImageC',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('ImageB',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('ImageA',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
